############## Spirit Configuration ##############



### Output Folders
[defaults]
output.file_tag = "<time>"
output.folder   = "output"

################## Hamiltonian ###################
[hamiltonian]
### External magnetic field vector[T]
external_field.magnitude  = 25.0
external_field.direction  = [0.0, 0.0, 1.0]

### Uniaxial anisotropy constant [meV]
anisotropy.magnitude      = 0.0
anisotropy.normal         = [0.0, 0.0, 1.0]

### Dipole-dipole interaction caclulation method
### (fft, fmm, cutoff, none)
ddi_method                = "none"

### DDI number of periodic images in (a b c)
ddi_n_periodic_images      = [4, 4, 4]

### DDI cutoff radius (if cutoff is used)
ddi_radius                 = 0.0

# If set to 1 zero padding is performed even for periodic directions, if set to 0 it is skipped for peridodic directions (improves speed and memory footprint)
ddi_pb_zero_padding        = true

### Pairs
pairs = """
i j   da db dc    Jij   Dij  Dijx Dijy Dijz
0 0    1  0  0   10.0   6.0   1.0  0.0  0.0
0 0    0  1  0   10.0   6.0   0.0  1.0  0.0
0 0    0  0  1   10.0   6.0   0.0  0.0  1.0
"""

### quadruplets
quadruplets = ""
################ End Hamiltonian #################



################### Geometry #####################
[geometry]
### µSpin
mu_s = 2.0

### Lattice constant for basis and translations
lattice_constant = 1.0

### The bravais lattice type
bravais_lattice = "sc"

### Number of basis cells along principal
### directions (a b c)
n_basis_cells = [100, 100, 1]

### Boundary_conditions (a b c): 0(open), 1(periodical)
boundary_conditions = [1, 1, 0]
################# End Geometry ###################

[logging]
output.folder = "."
### Save input parameters on State creation/deletion
save_input_initial  = false
save_input_final    = false

### Save atom positions on State creation/deletion
save_positions_initial = false
save_positions_final   = false

### Save exchange and DM neighbours on State creation/deletion
save_neighbours_initial = false
save_neighbours_final   = false

############### Logging Parameters ###############
### Levels of information
# 0 = ALL     - Anything
# 1 = SEVERE  - Severe error
# 2 = ERROR   - Error which can be handled
# 3 = WARNING - Possible unintended behaviour etc
# 4 = PARAMETER - Input parameter logging
# 5 = INFO      - Status information etc
# 6 = DEBUG     - Deeper status, eg numerical

### Print log messages to the console
log_to_console = true
### Print messages up to (including) log_console_level
console_level  = 5

### Save the log as a file
log_to_file  = true
### Save messages up to (including) log_file_level
file_level   = 4
############# End Logging Parameters #############



################# MC Parameters ##################
[method.mc]
### Maximum wall time for single simulation
### hh:mm:ss, where 0:0:0 is infinity
max_walltime     = "0:0:0"

### Seed for Random Number Generator
seed             = 20006

### Number of iterations
n_iterations     = 2000000
### Number of iterations after which to save
n_iterations_log = 2000
n_iterations_amortize = 1

### Temperature [K]
temperature      = 0

[method.mc.metropolis]
### Acceptance ratio
acceptance_ratio = 0.5

### Output configuration
[method.mc.output]
output_any     = true
output_initial = true
output_final   = true

energy_step                  = false
energy_archive               = true
energy_spin_resolved         = false
energy_divide_by_nspins      = true
energy_add_readability_lines = true

configuration_step     = true
configuration_archive  = false
configuration_filetype = 3
############### End MC Parameters ################



################ LLG Parameters ##################
[method.llg]
### Maximum wall time for single simulation
### hh:mm:ss, where 0:0:0 is infinity
max_walltime        = "0:0:0"

### Seed for Random Number Generator
seed                = 20006

### Number of iterations
n_iterations        = 2000000
### Number of iterations after which to save
n_iterations_log    = 2000
### Number of iterations that gets run with no checks or outputs (Increasing this boosts performance, especially in CUDA builds)
n_iterations_amortize = 1

### Temperature [K]
temperature                      = 0
temperature_gradient.magnitude   = 0
temperature_gradient.direction   = [1, 0, 0]

### Damping [none]
damping             = 0.3
### Non-adiabatic damping
beta                = 0.1

### Time step dt
dt                  = 1.0E-3

### Renormalize spins
renorm              = true

### Spin current model:
### 'gradient':  spin-orbit torque
### 'monolayer': spin-transfer torque
spin_current_model            = "monolayer"
### Spin current vector:
### proportional to the injected current density
spin_current_vector.magnitude = 0.0
spin_current_vector.direction = [1.0, 0.0, 0.0]

### Force convergence parameter
force_convergence   = 10e-9

### Output configuration
[method.llg.output]
any     = true
initial = true
final   = true

energy_step                  = false
energy_archive               = true
energy_spin_resolved         = false
energy_divide_by_nspins      = true
energy_add_readability_lines = true

configuration_step     = true
configuration_archive  = false
configuration_filetype = 3
############## End LLG Parameters ################



################ GNEB Parameters #################
[method.gneb]
### Maximum wall time for single simulation
### hh:mm:ss, where 0:0:0 is infinity
max_walltime        = "0:0:0"

spring_constant     = 1.0

### Bools 0 = false || 1 = true
renorm              = 1

### Number of GNEB Energy interpolations
n_energy_interpolations = 10

### Force convergence parameter
force_convergence   = 1e-7

### Number of iterations and saves
n_iterations          = 200000
n_iterations_log      = 200
n_iterations_amortize = 1

### Output configuration
[method.gneb.output]
any     = true
initial = false
final   = true

energies_step                  = false
energies_interpolated          = true
energies_divide_by_nspins      = true
energies_add_readability_lines = true

chain_step     = false
chain_filetype = 3
############## End GNEB Parameters ###############



################ MMF Parameters ##################
[method.mmf]
### Maximum wall time for single simulation
### hh:mm:ss, where 0:0:0 is infinity
max_walltime        = "0:0:0"

### Force convergence parameter
force_convergence   = 1e-7

### Number of iterations
n_iterations        = 200000
### Number of iterations after which to save
n_iterations_log    = 200
n_iterations_amortize = 1

### Number of modes
n_modes         = 10
### Mode to follow
n_mode_follow   = 0

### Output configuration
[method.mmf.output]
any     = true
initial = false
final   = true

energy_step                  = false
energy_archive               = true
energy_divide_by_nspins      = true
energy_add_readability_lines = true

configuration_step     = false
configuration_archive  = true
configuration_filetype = 3
############## End MMF Parameters ################



################ EMA Parameters ##################
[method.ema]
### Maximum wall time for single simulation
### hh:mm:ss, where 0:0:0 is infinity
max_walltime        = "0:0:0"

### Number of iterations
n_iterations        = 200000
### Number of iterations after which to save
n_iterations_log    = 200

### Number of modes
n_modes         = 10
### Mode to visualize
n_mode_follow   = 0

### Frequency of displacement
frequency = 0.02
### Amplitude of displacement
amplitude = 1

### Output configuration
[method.ema.output]
any     = false
initial = false
final   = false

energy_step                  = false
energy_archive               = true
energy_divide_by_nspins      = true
energy_spin_resolved         = false
energy_add_readability_lines = true

configuration_step     = false
configuration_archive  = true
configuration_filetype = 3
############## End EMA Parameters ################
